name: C/C++ CI for iOS

on:
  push:
    branches:
    - master
    - main
    - dev
    - dev/*
    - release/*
    - buildme/*

  pull_request:
    branches:
    - master
    - main
    - dev

  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-14]
        config: [release, debug]
        simulator: ["'iPhone 8'", "'iPad Air (3rd generation)'"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
      continue-on-error: true
    - name: build
      run: |
        if [[ "${{ matrix.os }}" == "macos-12" ]]; then
          export IOS_DEPLOYMENT_TARGET=12.0;
        elif [[ "${{ matrix.os }}" == "macos-14" ]]; then
          export IOS_DEPLOYMENT_TARGET=14.0;
        fi
        ./build-tests-ios.sh ${{ matrix.config }} ${{ matrix.simulator }}
